# cmake -P cmake/embed_hlsl.cmake -- src/shaders/*.hlsl -> one C++ header of
# raw-string literals (brief CLOUD-1 "shaders"). Run by add_custom_command in
# CMakeLists.txt at build time; no Python, no runtime file loading.
#
#   -DIN_DIR=<dir with the .hlsl files>
#   -DOUT=<header to write>
#   -DSHADERS=compute,display,post,gradient   (comma list; foo.hlsl -> kFooSrc)
#   -DPIECE_MAX=16000                         (optional)
#
# Each source becomes `static const char* k<Name>Src = R"hlsl(...)hlsl" ...;`.
# The text is embedded BYTE FOR BYTE (CRLF -> LF is the only change, which is
# what a raw string in a CRLF file compiles to anyway), cut into pieces of at
# most PIECE_MAX bytes on line boundaries: MSVC caps one literal at 16380
# bytes, and adjacent literals concatenate with nothing in between, so the
# split never changes the string. CMake string lengths/offsets are in bytes.
cmake_minimum_required(VERSION 3.20)
if(NOT DEFINED IN_DIR OR NOT DEFINED OUT OR NOT DEFINED SHADERS)
    message(FATAL_ERROR "embed_hlsl: need -DIN_DIR, -DOUT and -DSHADERS")
endif()
if(NOT DEFINED PIECE_MAX)
    set(PIECE_MAX 16000)
endif()
string(REPLACE "," ";" _names "${SHADERS}")

set(_out "// GENERATED by cmake/embed_hlsl.cmake from src/shaders/*.hlsl -- do not edit.\n")
string(APPEND _out "// Edit the .hlsl files; the build regenerates this header.\n#pragma once\n")
foreach(_n IN LISTS _names)
    set(_path "${IN_DIR}/${_n}.hlsl")
    if(NOT EXISTS "${_path}")
        message(FATAL_ERROR "embed_hlsl: ${_path} not found")
    endif()
    file(READ "${_path}" _txt)
    string(REPLACE "\r\n" "\n" _txt "${_txt}")
    string(FIND "${_txt}" ")hlsl\"" _bad)
    if(NOT _bad EQUAL -1)
        message(FATAL_ERROR "embed_hlsl: ${_n}.hlsl contains the raw-string terminator )hlsl\"")
    endif()
    string(SUBSTRING "${_n}" 0 1 _h)
    string(TOUPPER "${_h}" _h)
    string(SUBSTRING "${_n}" 1 -1 _t)
    set(_var "k${_h}${_t}Src")

    string(APPEND _out "\n// src/shaders/${_n}.hlsl\nstatic const char* ${_var} =\n")
    set(_count 0)
    string(LENGTH "${_txt}" _len)
    while(_len GREATER 0)
        if(_len GREATER PIECE_MAX)
            string(SUBSTRING "${_txt}" 0 ${PIECE_MAX} _head)
            string(FIND "${_head}" "\n" _nl REVERSE)
            if(_nl EQUAL -1)
                message(FATAL_ERROR "embed_hlsl: ${_n}.hlsl has a line longer than ${PIECE_MAX} bytes")
            endif()
            math(EXPR _cut "${_nl} + 1")
        else()
            set(_cut ${_len})
        endif()
        string(SUBSTRING "${_txt}" 0 ${_cut} _piece)
        string(SUBSTRING "${_txt}" ${_cut} -1 _txt)
        string(LENGTH "${_txt}" _len)
        string(APPEND _out "R\"hlsl(${_piece})hlsl\"\n")
        math(EXPR _count "${_count} + 1")
    endwhile()
    if(_count EQUAL 0)
        string(APPEND _out "\"\"\n")
    endif()
    string(APPEND _out ";\n")
endforeach()

file(WRITE "${OUT}" "${_out}")
